server:
  port: ${PORT:8882}
spring:
  profiles:
    active: dev
  redis:
    database: 0
    host: 127.0.0.1
    password: hospital.123redis
    pool:
      max-active: 300
      max-idle: 100
      max-wait: -1
      min-idle: 20
    port: 6379
    timeout: 60000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/medical_report?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: admin28270768
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://10.1.5.140:3312/medical_report?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: m4mr
#    password: m4mr_P@ss